# Experiment Specific
experiment_name: 'UNet_Abdomen_CT_Seg'
data_root: '/content/Dataset/abdominalDATA'
save_root: '/content/'
source_sites:
- 'CT'
resume_dir: ''
continue_train: False
total_epochs: 100
random_seed: 999
organ_list:
- 'Spleen'
- 'R.Kidney'
- 'L.Kidney'
- 'Liver'

# Dataloader Setting
img_size:
- 256
- 256
batch_size: 2
num_workers: 1

# Model 
arch: 'UNet'
use_prototype: False
update_prototype: False
input_dim: 3
feat_dim: 32
output_dim: 64
num_classes: 5

# Optim parameters
lr: 0.001

# Loss parameters
ce_ignore_index: -1
dice_ignore_index: 0

# display
save_epochs: 10
eval_epochs: 1
display_steps: 100
save_visuals: True

# test
test: False